# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-20 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180120_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(blank=True, default='abc', max_length=200),
            preserve_default=False,
        ),
    ]
